[package]
name = "ivsg"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29"
egui = "0.29"
egui_plot = "0.29"
num-complex = "0.4"
rustfft = "6.2"
csv = "1.3"
rfd = "0.15"
rand = "0.9.2"
image = "0.25.9"
